export const States: string[] = [
  'Capital Federal',
  'Buenos Aires',
  'Catamarca',
  'Chaco',
  'Chubut',
  'Córdoba',
  'Córdoba ( Capital )',
  'Corrientes',
  'Entre Ríos',
  'Entre Ríos ( Parana ) ',
  'Formosa',
  'Jujuy',
  'La Pampa',
  'La Pampa ( Santa Rosa ) ',
  'La Rioja',
  'Mendoza',
  'Misiones',
  'Neuquén',
  'Río Negro',
  'Salta',
  'San Juan',
  'San Luis',
  'Santa Cruz',
  'Santa Fe',
  'Santa Fe ( Capital y Rosario )',
  'Santiago del Estero',
  'Tierra del Fuego, Antártida e Islas del Atlántico Sur',
  'Tucumán',
];
